// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolGallery.DAL;

namespace SchoolGallery.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20190311115613_change_content_table")]
    partial class change_content_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolGallery.Models.AccountModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountID")
                        .IsRequired();

                    b.Property<string>("PassWord");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.HasKey("ID");

                    b.HasAlternateKey("AccountID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("SchoolGallery.Models.CategoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("NeedPassWord");

                    b.Property<int>("ParentID");

                    b.Property<string>("PassWord");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("SchoolGallery.Models.ContentModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accessories");

                    b.Property<int>("CategoryID");

                    b.Property<string>("Detail");

                    b.Property<string>("ModifiedIP");

                    b.Property<DateTime>("PublishTime");

                    b.Property<string>("PublisherID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("SchoolGallery.Models.VideoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
